<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9RFxIvL\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9RFxIvL/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container9RFxIvL.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container9RFxIvL\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container9RFxIvL\appAppKernelProdContainer([
    'container.build_hash' => '9RFxIvL',
    'container.build_id' => 'b772a105',
    'container.build_time' => 1747750769,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9RFxIvL');
