<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVRXkKcb\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVRXkKcb/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVRXkKcb.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVRXkKcb\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVRXkKcb\appAppKernelProdContainer([
    'container.build_hash' => 'VRXkKcb',
    'container.build_id' => '1e2c0319',
    'container.build_time' => 1742981147,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVRXkKcb');
